apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-frontend
  template:
    metadata:
      labels:
        app: shopping-frontend
    spec:
      containers:
      - name: shopping-frontend
        image: python:3.9-alpine
        command: ["python", "-m", "http.server", "8080"]
        workingDir: /app
      volumes:
      - name: frontend-html
        configMap:
          name: frontend-html
