apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shopping-api-postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: shopping-api
  template:
    metadata:
      labels:
        app: shopping-api
    spec:
      containers:
      - name: postgres
        image: postgres:13